### ISSUE TITLE
remove_duplicates.java

### ISSUE THREAD

**Issue by graysonstorer** [jbennett979/Open-Source-Project#16]
removeDuplicates does not identify duplicate values or insert them into the removed array, nor does it insert unique values into the unique array.

Steps to Reproduce

1. Reset the index in the initial for loop to i = 0;
2. Change forloop conditional to arr.size() instead of uniqueArr.size()
3. Change comparison indexes from i + 1 to i.

Expected Behavior :
description of where the array contains duplicate values, and an array with no duplicates. 
Actual Behavior A clear and concise description of what actually happened.
No duplicates were identified
Screenshots If applicable, add screenshots to help explain the issue/bug.

Additional Information

Operating System: MacOS 13.0
Browser: chrome
Version: most recent ?
Any other relevant information

This is a ***HIGH IMPACT*** issue

**Comment by SylvanFranklin** [comment]
fixed this thang.
